Secure an SPA workload docs
ddubson/docs-tap pull request #10
Opened 2023-03-20 20:39 UTC by ddubson

# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

It's best to PR to the most recent relevant branch and leave all the cherry-picking to the
writer, except where earlier branches require factual changes to the content.
For more information about the branches, see https://github.com/pivotal/docs-tap#branches

2023-03-28 10:03 UTC, mamachanko requested changes

2023-03-28 10:03 UTC, mamachanko commented on app-sso/app-operators/secure-spa-workload.hbs.md
> +launch a sample (fake) backend to allow for the frontend to launch.
**[thoughts, non-blocking]:** I find this to be not 💯 clear to me. Maybe it becomes clearer with terminology like _resource server_ etc. Also "fake" is a bit of a flag. Is it worth walking them through an _Nginx_ deployment when we expect most users to secure a _Java_ application?

2023-03-28 10:03 UTC, mamachanko commented on app-sso/app-operators/secure-spa-workload.hbs.md
> +launch a sample (fake) backend to allow for the frontend to launch.
After reading the section again I don't understand why I would want to "launch a sample backend". Sorry.

2023-03-28 10:04 UTC, mamachanko commented
**[issue]:** There are 4 `WIP` commits.

2023-03-28 13:43 UTC, ddubson commented on app-sso/app-operators/secure-spa-workload.hbs.md
> +_Example_: A `ClientRegistration` with name `angular-frontend` in namespace `my-apps` that is attached to an existing `AuthServer` with
The `_Example_` style I've been using in multiple places, on multiple pages. I can write a description before the example to make it easier to understand what is happening.

2023-03-28 13:47 UTC, ddubson commented on app-sso/app-operators/secure-spa-workload.hbs.md
> +launch a sample (fake) backend to allow for the frontend to launch.
`angular-frontend` expects to connect to a backend upon launch, otherwise it fails to start. For our use case, we don't care about a backend, but its required for the frontend to start, hence the faux backend instructions.

2023-03-28 15:23 UTC, mamachanko commented on app-sso/app-operators/secure-spa-workload.hbs.md
> +_Example_: A `ClientRegistration` with name `angular-frontend` in namespace `my-apps` that is attached to an existing `AuthServer` with
> The `_Example_` style I've been using in multiple places, on multiple pages [...]

Nice. It's consistent then!

2023-03-28 15:23 UTC, mamachanko commented on app-sso/app-operators/secure-spa-workload.hbs.md
> +launch a sample (fake) backend to allow for the frontend to launch.
_ack_

2023-03-29 12:01 UTC, mamachanko approved these changes
LGTM

2023-04-06 14:19 UTC, closed without merging