Appsso add release notes for 1.4
ddubson/docs-tap pull request #3
Opened 2022-12-13 18:16 UTC by ddubson

Release notes based on https://github.com/pivotal/sso4k8s/releases/tag/v3.0.0

2022-12-14 10:34 UTC, mamachanko requested changes
Almost there.

I recommend to use the full path when referring to fields of resources, rather than splitting them to fit English grammar. Prefer "Removed field `StuffBird.spec.call`" over "Removed `call` from `StuffBird.spec`".

Would you consider dropping the `experimental` label in the [LDAP section](https://github.com/ddubson/docs-tap/blob/appsso-add-release-notes-for-1.4/app-sso/service-operators/identity-providers.hbs.md#ldap-experimental) as well?

2022-12-14 10:34 UTC, mamachanko commented on release-notes.hbs.md
> +  to `AuthServer.spec.tls.disabled` by following instructions in [AppSSO migration guides](app-sso/upgrades/index.md#migration-guides).
```suggestion
- `AuthServer.spec.tls.disabled` is deprecated and marked for removal in the next release.  Please, migrate
  to `AuthServer.spec.tls.deactivated` by following instructions in [AppSSO migration guides](app-sso/upgrades/index.md#migration-guides).
```

2022-12-14 10:34 UTC, mamachanko commented on release-notes.hbs.md
> +in the next TAP version.
**[suggestion]**: I appreciate the _Known Issues_ section in TAP's release notes, but I am wondering if we should include this in AppSSO's component docs at least as well.

**[issue, nit]**: There're many more possible resources collisions than just this one. `AuthServer`-owned resources can collide as well. See [#184031220](https://www.pivotaltracker.com/story/show/184031220).

2022-12-14 10:34 UTC, mamachanko commented on release-notes.hbs.md
> +- LDAP error logging now contains proper error message.
**[suggestion, non-blocking]:** Use backticks and underscores to highlight CRs and names for visual delight.

2022-12-14 10:34 UTC, mamachanko commented on release-notes.hbs.md
> +- Removed deprecated field `issuerURI` from the `Authserver.spec`. Issuer URI is now dynamically generated based on TAP's `shared.ingress_domain` value.
> Issuer URI is now dynamically generated based on TAP's `shared.ingress_domain` value.

**[issue]**: This is only part of the truth. Instead, I suggest to link to `app-sso/service-operators/issuer-uri-and-tls.hbs.md`.

2022-12-14 10:34 UTC, mamachanko commented on release-notes.hbs.md
> +- Removed `spec.identityProviders.ldap.server` block.
```suggestion
- Removed `spec.identityProviders.ldap.server` field.
```

2022-12-14 10:34 UTC, mamachanko commented on release-notes.hbs.md
> +* LDAP features
```suggestion
* LDAP is now a _supported_ identity provider protocol. Learn [more](app-sso/service-operators/identity-providers.hbs.md#ldap-experimental).
```

2022-12-14 10:34 UTC, mamachanko commented on release-notes.hbs.md
> +* `tokenSignatures` in `AuthServer.spec` are now required to create an `AuthServer` resource.
```suggestion
* `AuthServer.spec.tokenSignatures` is now a required field.
```

2022-12-14 10:34 UTC, mamachanko commented on release-notes.hbs.md
> +* Added ability to configure AuthServer storage using ProvisionedService-style API.
**[issue]**: This does not do it justice at all. We want fanfares! And confetti! You can now bring your own Redis!!!111 That is worth a parade **and** a holiday.

2022-12-14 10:34 UTC, mamachanko commented on release-notes.hbs.md
> +* Added `tls.deactivated` to `AuthServer.spec` (deprecating `tls.disabled`).
```suggestion
* Added `AuthServer.spec.tls.deactivated` (deprecating `AuthServer.spec.tls.disabled`).
```

2022-12-14 10:34 UTC, mamachanko commented on release-notes.hbs.md
> +* Removed `LastParentGenerationWithRestart` from `AuthServer` Deployment.
**[issue]:** These are breaking changes and correctly listed in the relevant section.

2022-12-14 10:34 UTC, mamachanko commented on release-notes.hbs.md
> +- Removed field `LastParentGenerationWithRestart` from the `AuthServer` Deployment.
```suggestion
- Removed field `AuthServer.status.deployments.authServer.lastParentGenerationWithRestart`
```

2022-12-14 13:11 UTC, mamachanko commented on release-notes.hbs.md
> +* Certificate Authorities (CAs) are trusted per AuthServer. Configured at TAP level or per-AuthServer with `.spec.caCerts`.
```suggestion
* In addition to globally trusted CA certificates, granular trust can be extended with `AuthServer.spec.caCerts`.
```

2022-12-14 13:12 UTC, mamachanko commented on release-notes.hbs.md
> +#### <a id="1-4-0-appsso-nf"></a> Application Single Sign-On (AppSSO)
**[issue]:** The new features do not mention AppSSO participation in the `shared.ingress_issuer` with `default_authserver_clusterissuer`. When set, `AuthServer.spec.tls` is optional.

2022-12-14 13:48 UTC, ddubson commented on release-notes.hbs.md
> +in the next TAP version.
Shall we remove this completely? Since we now have a story to address this, this may not be "needed"

2022-12-14 13:51 UTC, ddubson commented on release-notes.hbs.md
> +* Removed `LastParentGenerationWithRestart` from `AuthServer` Deployment.
Will remove.

2022-12-14 13:52 UTC, ddubson commented on release-notes.hbs.md
> +* Added ability to configure AuthServer storage using ProvisionedService-style API.
Best I can do is move it up in the list and link to the storage docs page :-)

2022-12-14 14:06 UTC, ddubson commented on release-notes.hbs.md
> +in the next TAP version.
Removing block

2022-12-15 08:16 UTC, mamachanko approved these changes
LGTM

Yet,

> I recommend to use the full path when referring to fields of resources, rather than splitting them to fit English grammar. Prefer "Removed field StuffBird.spec.call" over "Removed call from StuffBird.spec".

still holds for improved readability.

I still think that

> Added ability to configure AuthServer storage using ProvisionedService-style API.

does not immediately tell me that I can bring my own Redis now.

2022-12-15 14:26 UTC, mamachanko approved these changes
🎉

2022-12-15 14:27 UTC, closed without merging