Appsso workload docs optimization
ddubson/docs-tap pull request #9
Opened 2023-03-15 19:40 UTC by ddubson

# Which other branches do you want a technical writer to cherry-pick this PR to (if any)?

It's best to PR to the most recent relevant branch and leave all the cherry-picking to the
writer, except where earlier branches require factual changes to the content.
For more information about the branches, see https://github.com/pivotal/docs-tap#branches

2023-03-17 19:27 UTC, sarahwalther commented on app-sso/app-operators/secure-spring-boot-workload.hbs.md
> +> **Note**: You may choose redirect URIs that are http or https based on your need.
[Maybe issue]: In the preview it looks like the `:` gets moved to the next line. Maybe we need to move it into the `**`, but I don't know how this comes out in the final version of the docs

2023-03-17 19:33 UTC, sarahwalther commented on app-sso/app-operators/secure-spring-boot-workload.hbs.md
> +>**Important**: While the name of the `ResourceClaim` may be anything you choose, the `Workload`g's service reference name
[maybe issue]: Same here as before, in the preview the `:` slips to the next line

2023-03-17 19:48 UTC, sarahwalther commented on app-sso/app-operators/workloads-and-appsso.hbs.md
> +    # ask your Service Operator for labels to target an `AuthServer`
[suggestion]: Should we have an alternative here? Like, for example tell the user that the command 
`kubectl label --list authserver/<your authserver> --namespace <your authserver's namespace>`
can show them options?

2023-03-17 19:51 UTC, candicenonsense commented on app-sso/app-operators/workloads-and-appsso.hbs.md
> +
This note: is too prominent at the beginning, sending you away before you get started.   Let's link the object name instead.

2023-03-17 19:52 UTC, candicenonsense commented on app-sso/app-operators/workloads-and-appsso.hbs.md
> +the credentials to your application to use as necessary.
Add a copy-pastable "here's how to check if the status is ready" block here

2023-03-17 20:02 UTC, sarahwalther commented
[praise]: I still find workloads confusing and overwhelming and I think this guide really walks users through how to apply one nicely. Including preparing the namespace. Nice!

2023-03-17 20:16 UTC, candicenonsense requested changes
Lots of good examples, let's get the language clearer here around all the introductions and explanations.

2023-03-17 20:16 UTC, candicenonsense commented on app-sso/app-operators/workloads-and-appsso.hbs.md
> +
s/has been applied/is ready/ -    "you may claim it using the tanzu CLI or applying a ResourceClaim yaml"

2023-03-17 20:16 UTC, candicenonsense commented on app-sso/app-operators/workloads-and-appsso.hbs.md
> +
s/will be referable within/can now be referenced by/

2023-03-17 20:16 UTC, candicenonsense commented on app-sso/app-operators/secure-spring-boot-workload.hbs.md
> +
s/procedure secure/procedure to secure a sample ..

Instead of "the Spring Boot Workload" - call it the AppSSO Spring Boot Sample workload or something more specific to what they'll be deploying

2023-03-17 20:16 UTC, candicenonsense commented on app-sso/app-operators/secure-spring-boot-workload.hbs.md
> +TAP GUI accelerators located on your TAP cluster.
Instead of "Get the accelerator" we can say "Get the sample application".   Switch "the appropriate" for "the appsso spring boot accelerator"..

2023-03-17 20:16 UTC, candicenonsense commented on app-sso/app-operators/secure-spring-boot-workload.hbs.md
> +
Instead of "Given/the following definition may apply" let's just define it -
This example defines a 'Workload' named "appsso-starter-java" in namespace 'my-apps' etc.  

We need to instruct the user to apply the yaml at the end of the section before proceeding

2023-03-17 20:16 UTC, candicenonsense commented on app-sso/app-operators/secure-spring-boot-workload.hbs.md
> +> Ensure to keep the suffix `/login/oauth2/code/{ClientRegistration.metadata.name}` format ([read more about Spring Security OAuth 2 Client library redirect URI format](./workloads-and-appsso.hbs.md#
Ensure to keep is a little clunky, suggest Keep the suffix formatted like this:

2023-03-17 20:16 UTC, candicenonsense commented on app-sso/app-operators/secure-spring-boot-workload.hbs.md
> +> `Workload` will run, but will not function properly.
Let's reverse this and be specific about what doesn't work - "If the service reference name does not match the (something) name in the client registration, the workload will present a redirect uri that is not accepted by the authserver."  Good candidate for the troubleshooting page, too.

2023-03-20 13:09 UTC, ddubson commented on app-sso/app-operators/workloads-and-appsso.hbs.md
> +    # ask your Service Operator for labels to target an `AuthServer`
Sounds good, I'll add this in.

2023-03-20 13:29 UTC, Kehrlann approved these changes
A few suggestions, nothing blocking.

2023-03-20 16:05 UTC, candicenonsense approved these changes
This looks great, only one place to add a capital letter.

2023-03-21 14:34 UTC, merged